services:
  - type: web
    name: seo-crawler
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: /opt/render/project/src/data
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: Aa456123
    disk:
      name: seo-crawler-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1